language: python
python:
  - "2.7"
  - "3.4"
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements.txt --upgrade --target ./lib
  - mv .env_copy .env
# command to run tests
script:
  - pytest test*
